### ISSUE TITLE
Epic: Reproducible NPM Packages for Noir

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#14]
As Noir Product Owner
I would like to publish Noir related EcmaScript (caugh: JavaScript) NPM packaged
so that applications can be developed in Browser
```[tasklist]
### Tasks
- [x] `noir_wasm` publishing
- [x] `acvm_js` publishing
- [x] `noir_abi_js` publishing
- [x] `noir-source-resolver` publishing
- [x] `noir_js` publishing
```

**Comment by kobyhallx** [comment]
As all those packages are now being published as latest/nightly this is ok to be closed. Please reopen as necessary.
