### ISSUE TITLE
Epic: Plookup Dynamic Arrays

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#18]
Enable dynamic arrays to make use of RAM/ROM opcodes when supported by the proving backend, heavily optimizing constraint counts hence proving speed of dynamic arrays.

```[tasklist]
- [ ] https://github.com/AztecProtocol/barretenberg/pull/417
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/pull/153
- [ ] https://github.com/noir-lang/acvm/pull/273
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/pull/154
- [ ] https://github.com/AztecProtocol/barretenberg/pull/483
- [ ] https://github.com/noir-lang/noir/pull/1393
- [ ] https://github.com/AztecProtocol/barretenberg/pull/520
- [ ] https://github.com/AztecProtocol/barretenberg/pull/528
- [ ] https://github.com/noir-lang/noir/pull/1282
```
