### ISSUE TITLE
Epic: Variable-length Keccak256

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#19]
```[tasklist]
- [ ] https://github.com/AztecProtocol/barretenberg/pull/441
- [ ] https://github.com/AztecProtocol/barretenberg/pull/476
- [ ] https://github.com/noir-lang/acvm/issues/313
- [ ] https://github.com/noir-lang/noir/pull/1393
- [ ] https://github.com/noir-lang/noir/issues/1399
```
