### ISSUE TITLE
Epic: Brilliq

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#20]
Unconstrained opcodes in ACVM

```[tasklist]
- [ ] https://github.com/noir-lang/acvm/issues/227
- [ ] https://github.com/noir-lang/acvm/issues/191
- [ ] https://github.com/noir-lang/noir/issues/1121
- [ ] https://github.com/noir-lang/acvm-docs/issues/1
```
