### ISSUE TITLE
Epic: Update Barretenberg

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#21]
Update the version of barretenberg consumed by Noir:

```[tasklist]
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/pull/212/
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/pull/213
- [ ] https://github.com/noir-lang/barretenberg-sys/pull/28
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/pull/214
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/pull/205
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/pull/215
- [ ] https://github.com/noir-lang/noir/issues/1489
```

**Comment by Savio-Sou** [comment]
Obsolete
