### ISSUE TITLE
Epic: Goblin Glider

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#25]
The Goblin Glider gaming / capture-the-flag contest.

```[tasklist]
### Blocked by
- [ ] https://github.com/noir-lang/acvm/pull/436
- [ ] https://github.com/noir-lang/noir/pull/1935
- [ ] https://github.com/noir-lang/Planning/issues/28
```

```[tasklist]
### Works
- [ ] Visual design
- [ ] Frontend - Incorporate designs
- [ ] Frontend - Add leaderboard
- [ ] Noir Program - Refactor with recursion
```
