### ISSUE TITLE
Epic: Noir.js MVP release

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#26]
As a Noir developer, I would like to make use of **one** Noir.js package to carry out everything Noir-related in JavaScript environments, so I can worry less about importing and managing multiple packages and ease my coding.

```[tasklist]
### Tasks
- [ ] Package [noir_wasm](https://github.com/noir-lang/noir_wasm) into Noir.js
- [ ] Package [acvm_js](https://github.com/noir-lang/acvm-simulator-wasm) into Noir.js
- [ ] Package [noir-source-resolver](https://github.com/noir-lang/noir-source-resolver) into Noir.js
- [ ] Package [acvm_to_barretenberg_witness_wasm](https://github.com/TomAFrench/acvm-to-barretenberg-witness-wasm) into Noir.js
- [ ] CI tests (if applicable)
- [ ] NPM release
```

Note:

Developers might want to prove and verify Noir programs using the package as well, but as Noir is proving backend agnostic that would be left as proving backend packages' responsibilities (e.g. bb.js) for now.

We can revisit the need for tighter integration with backend packages at a later date.

**Comment by kobyhallx** [comment]
What would be use cases one would came to this package for?

**Comment by Savio-Sou** [comment]
Intention is for this package to be the go-to for docs, tutorials, etc.

Where the individual packages would be documented in separate "advanced" sections.

**Comment by Savio-Sou** [comment]
Renamed for accuracy, as we should sync Noir.js's releases with Noir's / Nargo's rather than having its own set of version numbers.
