### ISSUE TITLE
Epic: Monorepo-ing

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#27]
First jab at combining repos.

```[tasklist]
### Transfer into [noir-lang/noir](https://github.com/noir-lang/noir)
- [ ] https://github.com/noir-lang/noir/issues/2227
- [x] [noir_wasm_testing](https://github.com/noir-lang/noir-wasm-testing)
- [ ] https://github.com/noir-lang/noir/issues/2439
- [ ] https://github.com/noir-lang/noir/issues/2523
```

```[tasklist]
### Transfer into [noir-lang/acvm](https://github.com/noir-lang/acvm)
- [ ] https://github.com/noir-lang/acvm/issues/458
```

**Comment by Savio-Sou** [comment]
@kobyhallx is this still relevant? Any updates to add?
