### ISSUE TITLE
Epic: Recursive aggregation in Next.js (i.e. in browser)

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#28]
As a Noir dApp developer interested in recursive aggregation (a.k.a. recursion, recursive proving), I would like to:

1. Fork [next-hardhat](https://github.com/noir-lang/noir-starter/tree/main/next-hardhat)
2. Prove my [recursive aggregation program (bin-test)](https://github.com/AztecProtocol/barretenberg/blob/master/ts/bin-test/src/main.nr) with custom inputs in browser using it

so that I can write Noir programs making use of recursive aggregation.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/1570
- [ ] [Ze's reported issue on Slack](https://aztecprotocol.slack.com/archives/C01CGB1KUN4/p1691487678747449?thread_ts=1691487473.211269&cid=C01CGB1KUN4)
- [ ] https://github.com/noir-lang/noir/issues/2557
- [ ] https://github.com/AztecProtocol/aztec-packages/pull/1855
- [ ] https://github.com/noir-lang/noir-starter/pull/49
- [ ] https://github.com/noir-lang/noir/issues/1244
```

**Comment by Savio-Sou** [comment]
For reference, @signorecello has put together [noir-recursion](https://github.com/signorecello/noir-recursion/), where getting it running should be equivalent to achieving steps (1) & (2).

**Comment by Savio-Sou** [comment]
Seems that the [recursion in headless browser test](https://github.com/noir-lang/noir/blob/8e93a5f4ccbcdb4fcd0f662d31ba4dd548aeae10/compiler/integration-tests/test/integration/browser/compile_prove_verify.test.ts#L44) is now [passing](https://github.com/noir-lang/noir/actions/runs/6167119941/job/16737601602#step:15:27).
