### ISSUE TITLE
Epic: UltraPlonk Benchmarks

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/Planning#3]
Benchmarks the gate count and proving performance of Noir programs in UltraPlonk vs TurboPlonk.

```[tasklist]
### Todo
- [ ] Determine what to test.
- [ ] Create testing repo + circuits
- [ ] Benchmark on e.g. Macbook (WASM vs Native)
```
